2020-01-03 23:08:54,524 INFO Current Process with pid 6482 with status running launched by the user ezafati
2020-01-03 23:08:54,995 ERROR {'exception_type': "<class 'systemutils.AlreadyExistError'>", 'message': '[\'  File "/home/ezafati/mesh_project/meshproject/tests/read_test.py", line 34, in <module>\\n    read_file("maillage5.txt", p)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 28, in read_file\\n    switch_case(fields, n_line, meshfile)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 53, in switch_case\\n    switcher.get(fields[2])(fields)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 45, in <lambda>\\n    \\\'LINE\\\': lambda fields: module_var.parsefile.make_boundary(fields, n_line),\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/MeshObjects/GeObjects.py", line 333, in make_boundary\\n    raise AlreadyExistError(f\\\'The label {label} is provided more than once\\\') from None\\n\']'}
NoneType: None
2020-01-03 23:10:39,121 INFO Current Process with pid 6503 with status running launched by the user ezafati
2020-01-03 23:10:39,599 ERROR {'exception_type': "<class 'systemutils.AlreadyExistError'>", 'message': '[\'  File "/home/ezafati/mesh_project/meshproject/tests/read_test.py", line 34, in <module>\\n    result = read_file("maillage5.txt", p)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 28, in read_file\\n    switch_case(fields, n_line, meshfile)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 53, in switch_case\\n    switcher.get(fields[2])(fields)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 45, in <lambda>\\n    \\\'LINE\\\': lambda fields: module_var.parsefile.make_boundary(fields, n_line),\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/MeshObjects/GeObjects.py", line 333, in make_boundary\\n    raise AlreadyExistError(f\\\'The label {label} is provided more than once\\\') from None\\n\']'}
NoneType: None
2020-01-03 23:12:04,715 INFO Current Process with pid 6534 with status running launched by the user ezafati
2020-01-03 23:12:05,205 ERROR {'exception_type': "<class 'systemutils.AlreadyExistError'>", 'message': '[\'  File "/home/ezafati/mesh_project/meshproject/tests/read_test.py", line 34, in <module>\\n    result = read_file("maillage5.txt", p)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 28, in read_file\\n    switch_case(fields, n_line, meshfile)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 53, in switch_case\\n    switcher.get(fields[2])(fields)\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/read_data.py", line 45, in <lambda>\\n    \\\'LINE\\\': lambda fields: module_var.parsefile.make_boundary(fields, n_line),\\n\', \'  File "/home/ezafati/mesh_project/meshproject/src/MeshObjects/GeObjects.py", line 333, in make_boundary\\n    raise AlreadyExistError(f\\\'The label {label} is provided more than once\\\') from None\\n\']The label L1 is provided more than once'}
NoneType: None
2020-01-04 22:25:11,480 INFO Current Process with pid 3006 with status running launched by the user ezafati
2020-01-04 22:25:12,869 INFO ############### END READ MESH FILE WITH SUCCESS   ###########################
2020-01-04 22:25:12,947 INFO DOMAIN WITH 103 POINTS IN BOUNDARY
2020-01-04 22:25:30,867 INFO PROCESS TERMINATES WITH NO MORE SKINNY TRIANGLE
2020-01-04 22:25:30,867 INFO MESH GENERATED WITH 263 POINTS
2020-01-04 22:26:11,634 INFO  Process  3006  terminates: user CPU time 3.7, system cpu time 1.58
2020-01-04 22:26:47,344 INFO Current Process with pid 3508 with status running launched by the user ezafati
2020-01-04 22:26:47,916 INFO ############### END READ MESH FILE WITH SUCCESS   ###########################
2020-01-04 22:26:48,058 INFO DOMAIN WITH 103 POINTS IN BOUNDARY
2020-01-04 22:27:05,722 INFO PROCESS TERMINATES WITH NO MORE SKINNY TRIANGLE
2020-01-04 22:27:05,722 INFO MESH GENERATED WITH 263 POINTS
2020-01-04 22:27:52,492 INFO  Process  3508  terminates: user CPU time 3.22, system cpu time 1.26
